### ISSUE TITLE
Add component library

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/cli#1]
Add command to write files from the component library to components path

**Comment by pellebjerkestrand** [comment]
It would be cool if this got the component from the repo on GitHub so we wouldn't need to ship the component library as a dependency. We then wouldn't need a new release of `cli` every time a component is updated or added either.

Each component might need a manifest (or some kind of file/folder convention) so we know which files to download, though 🤔

**Comment by asbjornh** [comment]
Yes!

I'll look into it

**Comment by asbjornh** [comment]
This has been added. Closing
