### ISSUE TITLE
Apply for a job

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/cli#14]
I would like to be able to run `creuna job` to "apply" for a job.

cli ➡️ Azure Function ➡️ Slack, possibly 🤔

The UI can be question based with `prompt` like `creuna new`.

**Comment by Reasonable-Solutions** [comment]
most of the backend stuff is done
https://github.com/Creuna-Oslo/azure-function-job-apply/pull/1
we should fix that up with proper deploys and not run it on my personal azure account.

This adds azure functions for applying, notifying on slack and also view the stored application blobs as html.

**Comment by asbjornh** [comment]
This issue is blocked by https://github.com/Creuna-Oslo/azure-function-job-apply/issues/2

**Comment by asbjornh** [comment]
~A thought: auth information to the azure function should probably not be checked into the repo. Need to figure something out with environment variables in travis or something.~ There's no auth. The URL needs to exist in `node_modules` anyway, so forget this :D
