### ISSUE TITLE
slow startup times

### ISSUE THREAD

**Issue by Reasonable-Solutions** [Creuna-Oslo/cli#28]
typically, `time node index.js` lands at almost 2 seconds. (doing an early show help, exit(0)) lands at several hundred ms. 
that's quite silly.
I've tried bundling it in a few different ways. I tried just converting the whole thing to es6 imports, no improvement.

**Comment by asbjornh** [comment]
I poked around a bit with this.

Just to get a baseline, `time node index.js` where `index.js` is an empty file completes in around 90ms on my machine.

`time creuna` and `time creuna -v` completes in around 170ms. `/bin/index.js` has three transitive dependencies from npm (`chalk`, `term-img` and `gradient-string`). When I removed those dependencies, `time creuna -v` ran at around 90ms. At least for `creuna` and `creuna -v` the extra 80ms seem to stem from using npm packages.

`/index.js` (the thing that runs all the other things) has tons of transitive dependencies. I tried to do some sort of "lazy loading" by putting calls to `require` inside of exported functions (as opposed to at the top of the file). This led to a reduction of about  500ms for `creuna new` (from ~800 to ~300) and around 200ms for any of the react scripts (from ~900 to ~700).

It seems to me like this is probably something we have to live with if we want to use npm packages. I'll implement a few tweaks where it'll give the most bang for the buck, but doing weird lazy loading tricks all over the app seems a bit excessive
