### ISSUE TITLE
Require latest version for 'creuna new'?

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/cli#7]
Should we require this package to be up to date before using `creuna new`?

This could introduce some complexity and new edge cases, but it would solve the edge case where a user hasn't used the tool for a long time and ends up initiating a new project with outdated files.

**Comment by pellebjerkestrand** [comment]
But isn't it the user's responsibility to check if their tools are out of date before using them?

I haven't decided if I think this would be too much hand holding or not. 🤔

**Comment by asbjornh** [comment]
Sure! But I still think it would be nice to be notified that new things exist before it's too late

**Comment by pellebjerkestrand** [comment]
I agree, but I don't think we should add code that refuses to run the tool unless the tool is the latest version.

**Comment by asbjornh** [comment]
This has been resolved with the notification of outdated version. Closing
